export default () => ({
  expo: {
    name: 'walletconnect-modal-react-native-example',
    slug: 'walletconnect-modal-react-native-example',
    version: '1.0.0',
    orientation: 'default',
    icon: './assets/icon.png',
    scheme: 'rnwalletconnectmodalexpo',
    userInterfaceStyle: 'automatic',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#ffffff',
    },
    assetBundlePatterns: ['**/*'],
    ios: {
      bundleIdentifier: 'com.walletconnect.modal.rnexample',
      supportsTablet: true,
      infoPlist: {
        LSApplicationQueriesSchemes: [
          'metamask',
          'trust',
          'safe',
          'rainbow',
          'uniswap',
          'zerion',
          'imtokenv2',
          'argent',
          'spot',
          'omni',
          'dfw',
          'tpoutside',
          'robinhood-wallet',
          'frontier',
          'blockchain-wallet',
          'safepalwallet',
          'bitkeep',
          'zengo',
          'oneinch',
          'bnc',
          'exodus',
          'ledgerlive',
          'mewwallet',
          'awallet',
          'keyring',
          'lobstr',
          'ontoprovider',
          'mathwallet',
          'unstoppabledomains',
          'obvious',
          'fireblocks-wc',
          'ambire',
          'internetmoney',
          'walletnow',
          'bitcoincom',
        ],
      },
    },
    android: {
      package: 'com.walletconnect.modal.rnexample',
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#ffffff',
      },
    },
    web: {
      favicon: './assets/favicon.png',
    },
    extra: {
      eas: {
        projectId: 'f477ced2-c06e-470c-adcc-2c997a90cc4e',
      },
    },
    updates: {
      url: 'https://u.expo.dev/f477ced2-c06e-470c-adcc-2c997a90cc4e',
    },
    runtimeVersion: {
      policy: 'sdkVersion',
    },
    owner: 'nacho.walletconnect',
  },
});
