blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/orgs/WalletConnect/discussions/
      about: Looking for help with your app? Please refer to the Wallet Connect community's support resources.
    - name: 🚀 Discussions and Proposals
      url: https://github.com/orgs/WalletConnect/discussions
      about: Discuss the future of WalletConnect Modal SDK in the Wallet Connect community's discussions and proposals repository.
